name: Lint and Format

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Clear old preinstalled versions
        run: sudo apt remove --purge clang*

      - name: Install python dependencies
        run: pip install meson

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build \
              cmake libgtkmm-3.0-dev libglfw3-dev libglew-dev \
              libglm-dev libgl-dev libepoxy-dev libgtest-dev

      - name: echo
        run: where clang++-21

      - name: Configure Meson
        run: CXX=clang++-21 meson setup buildDir

      - name: Compile
        run: meson compile -C buildDir -j 10

      - name: Check meson formatting
        run: meson format -r -i

      - name: Run clang-format
        run: find ./src -type f -regex ".*\.\(cpp\|hpp\)" -print0 | xargs -0 clang-format-21 -i --style=file --Werror

      - name: Run clang-tidy
        run: find ./src -type f -regex ".*\.\(cpp\|hpp\)" -print0 | xargs -0 clang-tidy-21 -p buildDir --warnings-as-errors='*'
