name: Meson Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_dispatch:  # temporary

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install python dependencies
        run: pip install meson

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21 all

      - name: Update alternatives
        run: |
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 1
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-21 1
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-21 1
          clang++ --version
          clang-tidy --version
          clang-format --version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build \
              cmake libgtkmm-3.0-dev libglfw3-dev libglew-dev \
              libglm-dev libgl-dev libepoxy-dev libgtest-dev

      - name: Configure Meson
        run: CXX=clang++ meson setup buildDir

      - name: Run Tests
        run: meson test -C buildDir -j 10 --print-errorlogs
